apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-datasources
  namespace: default
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service.default.svc.cluster.local:9090
        isDefault: true
        editable: false
        jsonData:
          timeInterval: '15s'
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-service:3100
        editable: false
        jsonData:
          maxLines: 1000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-dashboards
  namespace: default
data:
  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: subul-dashboards
        type: file
        disableDeletion: true
        updateIntervalSeconds: 30
        allowUiUpdates: false
        options:
          path: /var/lib/grafana/dashboards
